# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4f78ef44ccd55dad3bed6fe7318d533b27ea17515dcc4de2cbd9d406c3e5c831b57afd486edd6d9a14783fbd22782f8b84ee8b6d4ba8fb8b018bc0d7dbabb48

test:
  secret_key_base: 2772c99eabdbcf19ba5a6023feb5a6acc6c605be63ca3c8a97723ccb7507ffe01b68eaf30493f3bbc144f2be042ff69ef937ef37f07f36cd35495c6c5fd16314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
